// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StravaHeatmap.Api.Data;

#nullable disable

namespace StravaHeatmap.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260930202711_AddActivity")]
    partial class AddActivity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("StravaHeatmap.Api.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AverageSpeed")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("DistanceMeters")
                        .HasColumnType("REAL");

                    b.Property<int>("ElapsedTimeSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MovingTimeSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("SportType")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("StravaActivityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StravaConnectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SummaryPolyline")
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalElevationGain")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StravaActivityId")
                        .IsUnique();

                    b.HasIndex("StravaConnectionId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("StravaHeatmap.Api.Models.StravaConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("AthleteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AthleteName")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId")
                        .IsUnique();

                    b.ToTable("StravaConnections");
                });

            modelBuilder.Entity("StravaHeatmap.Api.Models.Activity", b =>
                {
                    b.HasOne("StravaHeatmap.Api.Models.StravaConnection", "Connection")
                        .WithMany()
                        .HasForeignKey("StravaConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Connection");
                });
#pragma warning restore 612, 618
        }
    }
}
